Added support for Django 4.1
cdriehuys/django-rest-email-auth pull request #104
Opened 2023-03-23 14:38 UTC by mlodic

2023-03-23 14:39 UTC, mlodic commented
I added this. I am trying to have this explicitly support new Django versions so we can use it in modern Django projects.

2023-03-23 14:55 UTC, cdriehuys commented
Thanks for the PR! I'd be willing to cut down the supported versions in order to get Django 4 compatibility. From [Django's docs](https://www.djangoproject.com/download/#supported-versions), it looks like the 3.2 LTS and any Django 4 version is all that's supported right now.

2023-03-23 15:04 UTC, cdriehuys commented
Great, thanks. I think we could also decrease the number of test environments needed. Based on [Django's supported Python versions](https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django), I think we could get away with:

| Django Version | Python Version(s) |
| ----------------|------------------ |
| 3.2 | 3.6, 3.10 |
| 4.x | 3.8, 3.11 |

2023-03-23 15:10 UTC, cdriehuys requested changes

2023-03-23 15:10 UTC, cdriehuys commented on setup.py
> +        "Django >= 2.2, <= 4.2",
```suggestion
        "Django >= 3.2, <= 4.2",
```

2023-03-23 15:10 UTC, cdriehuys commented on docs/CHANGELOG.rst
> +    2.2, 3.2, and 4.0, but all versions after 2.2 should work.
```suggestion
  * :issue:`97`: Added support for Django 4. We explicitly test against Django
    3.2, 4.0, and 4.1, but all versions after 3.2 should work.
```

2023-03-23 15:10 UTC, cdriehuys commented on setup.py
>          "djangorestframework >= 3.10",
DRF 3.14 is the first version to support Django 3.2, 4.0, and 4.1.

```suggestion
        "djangorestframework >= 3.14",
```

2023-03-23 15:20 UTC, cdriehuys approved these changes

2023-03-23 15:32 UTC, cdriehuys commented
Looks like `black` is failing. This should really be separated into another build since we don't need to check the style for every Python version. I can take a look at doing this later if you don't mind waiting a bit.

2023-03-24 16:08 UTC, merged

2023-03-24 16:09 UTC, cdriehuys commented
I went ahead and merged this with the tests failing. I'll clean those up and then cut a release when I get a chance. Thanks again for the PR.

2023-03-24 16:22 UTC, mlodic commented
thank you!